fixes:
  - "/home/jenkins/kafka-to-nexus/::"  # Corrects coverage paths to be relative to repo root

ignore:
  - "src/tests"
  - "*_generated.h"
  - "*/src/date/*"
  - "*/.conan/data/*"
  - "*/usr/*"

comment:
  - layout: "header, diff, tree, changes, sunburst"
  - require_changes: false
