fixes:
  - "/home/jenkins/kafka-to-nexus/::"  # Corrects coverage paths to be relative to repo root

ignore:
  - src/tests/.*
  - .*_generated.h

comment:
  layout: "header, diff, tree, changes, sunburst"
  require_changes: false
