fixes:
  - "/home/jenkins/kafka-to-nexus/::"  # Corrects coverage paths to be relative to repo root

ignore:
  - "src/tests"

comment:
  - layout: "header, diff, tree, changes, sunburst"
  - require_changes: false
