version: '3.7'

services:
  kafka:
    image: wurstmeister/kafka:2.12-2.1.0
    depends_on:
      - zookeeper
    hostname: kafka
    platform: linux/amd64
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 10000000
      KAFKA_BROKER_ID: 0
      KAFKA_CREATE_TOPICS: "local_filewriter_pool:1:1,local_filewriter_status:1:1,instrument_topic:1:1,f144_data:1:1,ev44_data:3:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  zookeeper:
    image: zookeeper:3.4
    platform: linux/amd64
