version: '2'

services:
  filewriter1:
    image: kafka-to-nexus:latest
    network_mode: "host"
    environment:
      CONFIG_FILE: "/file_writer_config.ini"
    volumes:
      - ./config-files/file_writer_config1.ini:/file_writer_config.ini
      - ./output-files/:/output-files/
      - ./logs/:/filewriter_logs/

  filewriter2:
    image: kafka-to-nexus:latest
    network_mode: "host"
    environment:
      CONFIG_FILE: "/file_writer_config.ini"
    volumes:
      - ./config-files/file_writer_config2.ini:/file_writer_config.ini
      - ./output-files/:/output-files/
      - ./logs/:/filewriter_logs/
