version: '2'

services:
  event-producer:
    image: screamingudder/nexus-streamer:456f5a6
    network_mode: "host"
    environment:
      CONFIG_FILE: "/streamer_config.ini"
      KAFKA_BROKER: "localhost"
    volumes:
    - ./config-files/streamer_config.ini:/streamer_config.ini
    - ./config-files/SANS2D_reduced_with_geometry.nxs:/SANS2D_reduced_with_geometry.nxs

  filewriter:
    depends_on:
      - event-producer
    image: kafka-to-nexus:latest
    network_mode: "host"
    environment:
      CONFIG_FILE: "/file_writer_config.ini"
    volumes:
    - ./config-files/file_writer_config.ini:/file_writer_config.ini
    - ./output-files/:/output-files/
    - ./logs/:/filewriter_logs/
