version: '2'

services:
  filewriter:
    image: kafka-to-nexus:latest
    network_mode: "host"
    environment:
      CONFIG_FILE: "/file_writer_config_static_data.ini"
    volumes:
      - ./config-files/file_writer_config_static_data.ini:/file_writer_config_static_data.ini
      - ./output-files/:/output-files/
      - ./logs/:/filewriter_logs/
