version: '2'

services:
  kafka:
    image: wurstmeister/kafka:1.0.0
    depends_on:
      - zookeeper
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 20000000
      KAFKA_BROKER_ID: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  zookeeper:
    image: zookeeper:3.4

  filewriter:
    image: kafka-to-nexus:latest
    depends_on:
      - kafka
    network_mode: "host"
    environment:
      CONFIG_FILE: "/file_writer_config_static_data.ini"
    volumes:
      - ./config-files/file_writer_config_static_data.ini:/file_writer_config_static_data.ini
      - ./output-files/:/output-files/
      - ./logs/:/filewriter_logs/
