set(REQUIRE_GTEST FALSE CACHE BOOL "Require Google Test")
if (REQUIRE_GTEST)
	find_path(path_googletest_repository NAMES "googletest/include/gtest/gtest.h" HINTS "${GOOGLETEST_REPOSITORY_DIR}" "../googletest")
	if (path_googletest_repository)
		set(path_include_gtest "${path_googletest_repository}/googletest/include")
		set(path_include_gmock "${path_googletest_repository}/googlemock/include")
		message(STATUS "Google Test repository at ${path_googletest_repository}")
		message(STATUS "path_include_gtest: ${path_include_gtest}")
		message(STATUS "path_include_gmock: ${path_include_gmock}")
		set(have_gtest 1)
		add_subdirectory(${path_googletest_repository} googletest)
	else()
		message(FATAL_ERROR "Google Test required but not found")
	endif()
endif()

function(add_gtest_to_target tgt)
	if (have_gtest)
		add_dependencies(${tgt} gtest)
		target_compile_definitions(${tgt} PRIVATE HAVE_GTEST=1)
		target_include_directories(${tgt} PRIVATE ${path_include_gtest} ${path_include_gmock})
		target_link_libraries(${tgt} gtest_main gmock_main)
	endif()
endfunction()
